In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Gathering Info about the Dataset

- i will import and read the dataset. 
- explore the structure of the dataset 
- and see what kind of values are present in each column

In [2]:
df = pd.read_csv("data.csv")

In [3]:
df.head()

,Country Name,Country Code,year,Access to electricity (% of population),"Access to electricity, rural (% of rural population)",Agricultural irrigated land (% of total agricultural land),Agricultural land (% of land area),Agricultural land (sq. km),"Agricultural machinery, tractors","Agricultural machinery, tractors per 100 sq. km of arable land",...,Permanent cropland (% of land area),"Population, total",Rural land area (sq. km),Rural land area where elevation is below 5 meters (% of total land area),Rural land area where elevation is below 5 meters (sq. km),Rural population,Rural population (% of total population),Rural population growth (annual %),Rural population living in areas where elevation is below 5 meters (% of total population),Surface area (sq. km)
0,Afghanistan,AFG,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8996973.0,NaN,NaN,NaN,8241137.0,91.599,NaN,NaN,NaN
1,Afghanistan,AFG,1961,NaN,NaN,NaN,57.745918,377000.0,120.0,0.156863,...,0.076586,9169410.0,NaN,NaN,NaN,8373138.0,91.316,1.589040,NaN,652860.0
2,Afghanistan,AFG,1962,NaN,NaN,NaN,57.837821,377600.0,150.0,0.194805,...,0.091903,9351441.0,NaN,NaN,NaN,8512056.0,91.024,1.645479,NaN,652860.0
3,Afghanistan,AFG,1963,NaN,NaN,NaN,57.914407,378100.0,200.0,0.258065,...,0.091903,9543205.0,NaN,NaN,NaN,8657977.0,90.724,1.699758,NaN,652860.0
4,Afghanistan,AFG,1964,NaN,NaN,NaN,58.010906,378730.0,200.0,0.256410,...,0.111816,9744781.0,NaN,NaN,NaN,8810646.0,90.414,1.747967,NaN,652860.0

In [4]:
df. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16104 entries, 0 to 16103
Data columns (total 55 columns):
 #   Column                                                                                      Non-Null Count  Dtype
---  ------                                                                                      --------------  -----
 0   Country Name                                                                                16104 non-null  object
 1   Country Code                                                                                16104 non-null  object
 2   year                                                                                        16104 non-null  int64
 3   Access to electricity (% of population)                                                     6174 non-null   float64
 4   Access to electricity, rural (% of rural population)                                        5959 non-null   float64
 5   Agricultural irrigated land (% of total agricultural land)                                  856 non-null    float64
 6   Agricultural land (% of land area)                                                          13055 non-null  float64
 7   Agricultural land (sq. km)                                                                  13232 non-null  float64
 8   Agricultural machinery, tractors                                                            7783 non-null   float64
 9   Agricultural machinery, tractors per 100 sq. km of arable land                              7424 non-null   float64
 10  Agricultural methane emissions (% of total)                                                 9715 non-null   float64
 11  Agricultural methane emissions (thousand metric tons of CO2 equivalent)                     10520 non-null  float64
 12  Agricultural nitrous oxide emissions (% of total)                                           9754 non-null   float64
 13  Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)               10520 non-null  float64
 14  Agricultural raw materials exports (% of merchandise exports)                               8969 non-null   float64
 15  Agricultural raw materials imports (% of merchandise imports)                               8997 non-null   float64
 16  Agriculture, forestry, and fishing, value added (% of GDP)                                  9694 non-null   float64
 17  Agriculture, forestry, and fishing, value added (current US$)                               9636 non-null   float64
 18  Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)               636 non-null    float64
 19  Arable land (% of land area)                                                                12918 non-null  float64
 20  Arable land (hectares per person)                                                           12892 non-null  float64
 21  Arable land (hectares)                                                                      10513 non-null  float64
 22  Average precipitation in depth (mm per year)                                                2068 non-null   float64
 23  Birth rate, crude (per 1,000 people)                                                        14515 non-null  float64
 24  Cereal production (metric tons)                                                             11819 non-null  float64
 25  Cereal yield (kg per hectare)                                                               11781 non-null  float64
 26  CPIA gender equality rating (1=low to 6=high)                                               1738 non-null   float64
 27  Crop production index (2004-2006 = 100)                                                     12570 non-null  float64
 28  Death rate, crude (per 1,000 people)                                                        14492 non-null  float64
 29  Employment in agriculture (% of total employment) (modeled ILO estimate)                    6990 non-null   float64
 30  Employment in agriculture, female (% of female employment) (modeled ILO estimate)           6990 non-null   float64
 31  Employment in agriculture, male (% of male employment) (modeled ILO estimate)               6990 non-null   float64
 32  Fertilizer consumption (% of fertilizer production)                                         1825 non-null   float64
 33  Fertilizer consumption (kilograms per hectare of arable land)                               2987 non-null   float64
 34  Food production index (2004-2006 = 100)                                                     12684 non-null  float64
 35  Forest area (% of land area)                                                                6857 non-null   float64
 36  Forest area (sq. km)                                                                        6893 non-null   float64
 37  GDP per capita (current US$)                                                                12369 non-null  float64
 38  Land area (sq. km)                                                                          14935 non-null  float64
 39  Land under cereal production (hectares)                                                     11792 non-null  float64
 40  Literacy rate, adult total (% of people ages 15 and above)                                  2504 non-null   float64
 41  Livestock production index (2004-2006 = 100)                                                12649 non-null  float64
 42  Mineral rents (% of GDP)                                                                    10837 non-null  float64
 43  Mortality rate, infant (per 1,000 live births)                                              11835 non-null  float64
 44  Net migration                                                                               2868 non-null   float64
 45  Permanent cropland (% of land area)                                                         12344 non-null  float64
 46  Population, total                                                                           15671 non-null  float64
 47  Rural land area (sq. km)                                                                    675 non-null    float64
 48  Rural land area where elevation is below 5 meters (% of total land area)                    669 non-null    float64
 49  Rural land area where elevation is below 5 meters (sq. km)                                  675 non-null    float64
 50  Rural population                                                                            15551 non-null  float64
 51  Rural population (% of total population)                                                    15592 non-null  float64
 52  Rural population growth (annual %)                                                          14847 non-null  float64
 53  Rural population living in areas where elevation is below 5 meters (% of total population)  675 non-null    float64
 54  Surface area (sq. km)                                                                       14935 non-null  float64
dtypes: float64(52), int64(1), object(2)
memory usage: 6.8+ MB

# Data Cleaning and Preprocessing

In [5]:
df.shape
df.isna()

,Country Name,Country Code,year,Access to electricity (% of population),"Access to electricity, rural (% of rural population)",Agricultural irrigated land (% of total agricultural land),Agricultural land (% of land area),Agricultural land (sq. km),"Agricultural machinery, tractors","Agricultural machinery, tractors per 100 sq. km of arable land",...,Permanent cropland (% of land area),"Population, total",Rural land area (sq. km),Rural land area where elevation is below 5 meters (% of total land area),Rural land area where elevation is below 5 meters (sq. km),Rural population,Rural population (% of total population),Rural population growth (annual %),Rural population living in areas where elevation is below 5 meters (% of total population),Surface area (sq. km)
0,False,False,False,True,True,True,True,True,True,True,...,True,False,True,True,True,False,False,True,True,True
1,False,False,False,True,True,True,False,False,False,False,...,False,False,True,True,True,False,False,False,True,False
2,False,False,False,True,True,True,False,False,False,False,...,False,False,True,True,True,False,False,False,True,False
3,False,False,False,True,True,True,False,False,False,False,...,False,False,True,True,True,False,False,False,True,False
4,False,False,False,True,True,True,False,False,False,False,...,False,False,True,True,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16099,False,False,False,False,False,True,False,False,True,True,...,False,False,True,True,True,False,False,False,True,False
16100,False,False,False,False,False,True,True,True,True,True,...,True,False,True,True,True,False,False,False,True,False
16101,False,False,False,False,False,True,True,True,True,True,...,True,False,True,True,True,False,False,False,True,False
16102,False,False,False,True,True,True,True,True,True,True,...,True,False,True,True,True,False,False,False,True,True
16103,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [6]:
peekdata = df.iloc[: , 3:].copy()

In [7]:
info_missing_values= peekdata.isna().sum() / len(peekdata)

In [8]:
print(info_missing_values)

Access to electricity (% of population)                                                       0.616617
Access to electricity, rural (% of rural population)                                          0.629968
Agricultural irrigated land (% of total agricultural land)                                    0.946846
Agricultural land (% of land area)                                                            0.189332
Agricultural land (sq. km)                                                                    0.178341
Agricultural machinery, tractors                                                              0.516704
Agricultural machinery, tractors per 100 sq. km of arable land                                0.538997
Agricultural methane emissions (% of total)                                                   0.396734
Agricultural methane emissions (thousand metric tons of CO2 equivalent)                       0.346746
Agricultural nitrous oxide emissions (% of total)                                             0.394312
Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)                 0.346746
Agricultural raw materials exports (% of merchandise exports)                                 0.443058
Agricultural raw materials imports (% of merchandise imports)                                 0.441319
Agriculture, forestry, and fishing, value added (% of GDP)                                    0.398038
Agriculture, forestry, and fishing, value added (current US$)                                 0.401639
Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)                 0.960507
Arable land (% of land area)                                                                  0.197839
Arable land (hectares per person)                                                             0.199454
Arable land (hectares)                                                                        0.347181
Average precipitation in depth (mm per year)                                                  0.871585
Birth rate, crude (per 1,000 people)                                                          0.098671
Cereal production (metric tons)                                                               0.266083
Cereal yield (kg per hectare)                                                                 0.268443
CPIA gender equality rating (1=low to 6=high)                                                 0.892077
Crop production index (2004-2006 = 100)                                                       0.219449
Death rate, crude (per 1,000 people)                                                          0.100099
Employment in agriculture (% of total employment) (modeled ILO estimate)                      0.565946
Employment in agriculture, female (% of female employment) (modeled ILO estimate)             0.565946
Employment in agriculture, male (% of male employment) (modeled ILO estimate)                 0.565946
Fertilizer consumption (% of fertilizer production)                                           0.886674
Fertilizer consumption (kilograms per hectare of arable land)                                 0.814518
Food production index (2004-2006 = 100)                                                       0.212370
Forest area (% of land area)                                                                  0.574205
Forest area (sq. km)                                                                          0.571970
GDP per capita (current US$)                                                                  0.231930
Land area (sq. km)                                                                            0.072591
Land under cereal production (hectares)                                                       0.267760
Literacy rate, adult total (% of people ages 15 and above)                                    0.844511
Livestock production index (2004-2006 = 100)                                                  0.214543
Mineral rents (% of GDP)                                                                      0.327062
Mortality rate, infant (per 1,000 live births)                                                0.265089
Net migration                                                                                 0.821908
Permanent cropland (% of land area)                                                           0.233482
Population, total                                                                             0.026888
Rural land area (sq. km)                                                                      0.958085
Rural land area where elevation is below 5 meters (% of total land area)                      0.958458
Rural land area where elevation is below 5 meters (sq. km)                                    0.958085
Rural population                                                                              0.034339
Rural population (% of total population)                                                      0.031793
Rural population growth (annual %)                                                            0.078055
Rural population living in areas where elevation is below 5 meters (% of total population)    0.958085
Surface area (sq. km)                                                                         0.072591
dtype: float64

In [9]:
type(info_missing_values) # as we can see - we get a Pandas series as an output

pandas.core.series.Series

In [10]:
info_missing_values.dtype # we know that the series is of a float type

dtype('float64')

In [11]:
s= info_missing_values [ info_missing_values >= 0.5] 
#filtering the columns that have more than 80 percent NaN values

In [12]:
s

Access to electricity (% of population)                                                       0.616617
Access to electricity, rural (% of rural population)                                          0.629968
Agricultural irrigated land (% of total agricultural land)                                    0.946846
Agricultural machinery, tractors                                                              0.516704
Agricultural machinery, tractors per 100 sq. km of arable land                                0.538997
Annual freshwater withdrawals, agriculture (% of total freshwater withdrawal)                 0.960507
Average precipitation in depth (mm per year)                                                  0.871585
CPIA gender equality rating (1=low to 6=high)                                                 0.892077
Employment in agriculture (% of total employment) (modeled ILO estimate)                      0.565946
Employment in agriculture, female (% of female employment) (modeled ILO estimate)             0.565946
Employment in agriculture, male (% of male employment) (modeled ILO estimate)                 0.565946
Fertilizer consumption (% of fertilizer production)                                           0.886674
Fertilizer consumption (kilograms per hectare of arable land)                                 0.814518
Forest area (% of land area)                                                                  0.574205
Forest area (sq. km)                                                                          0.571970
Literacy rate, adult total (% of people ages 15 and above)                                    0.844511
Net migration                                                                                 0.821908
Rural land area (sq. km)                                                                      0.958085
Rural land area where elevation is below 5 meters (% of total land area)                      0.958458
Rural land area where elevation is below 5 meters (sq. km)                                    0.958085
Rural population living in areas where elevation is below 5 meters (% of total population)    0.958085
dtype: float64

In [13]:
#since we have peekdata as our dataset i will drop the above columns in peekdata

df = df.drop(columns = s.keys())

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16104 entries, 0 to 16103
Data columns (total 34 columns):
 #   Column                                                                         Non-Null Count  Dtype
---  ------                                                                         --------------  -----
 0   Country Name                                                                   16104 non-null  object
 1   Country Code                                                                   16104 non-null  object
 2   year                                                                           16104 non-null  int64
 3   Agricultural land (% of land area)                                             13055 non-null  float64
 4   Agricultural land (sq. km)                                                     13232 non-null  float64
 5   Agricultural methane emissions (% of total)                                    9715 non-null   float64
 6   Agricultural methane emissions (thousand metric tons of CO2 equivalent)        10520 non-null  float64
 7   Agricultural nitrous oxide emissions (% of total)                              9754 non-null   float64
 8   Agricultural nitrous oxide emissions (thousand metric tons of CO2 equivalent)  10520 non-null  float64
 9   Agricultural raw materials exports (% of merchandise exports)                  8969 non-null   float64
 10  Agricultural raw materials imports (% of merchandise imports)                  8997 non-null   float64
 11  Agriculture, forestry, and fishing, value added (% of GDP)                     9694 non-null   float64
 12  Agriculture, forestry, and fishing, value added (current US$)                  9636 non-null   float64
 13  Arable land (% of land area)                                                   12918 non-null  float64
 14  Arable land (hectares per person)                                              12892 non-null  float64
 15  Arable land (hectares)                                                         10513 non-null  float64
 16  Birth rate, crude (per 1,000 people)                                           14515 non-null  float64
 17  Cereal production (metric tons)                                                11819 non-null  float64
 18  Cereal yield (kg per hectare)                                                  11781 non-null  float64
 19  Crop production index (2004-2006 = 100)                                        12570 non-null  float64
 20  Death rate, crude (per 1,000 people)                                           14492 non-null  float64
 21  Food production index (2004-2006 = 100)                                        12684 non-null  float64
 22  GDP per capita (current US$)                                                   12369 non-null  float64
 23  Land area (sq. km)                                                             14935 non-null  float64
 24  Land under cereal production (hectares)                                        11792 non-null  float64
 25  Livestock production index (2004-2006 = 100)                                   12649 non-null  float64
 26  Mineral rents (% of GDP)                                                       10837 non-null  float64
 27  Mortality rate, infant (per 1,000 live births)                                 11835 non-null  float64
 28  Permanent cropland (% of land area)                                            12344 non-null  float64
 29  Population, total                                                              15671 non-null  float64
 30  Rural population                                                               15551 non-null  float64
 31  Rural population (% of total population)                                       15592 non-null  float64
 32  Rural population growth (annual %)                                             14847 non-null  float64
 33  Surface area (sq. km)                                                          14935 non-null  float64
dtypes: float64(31), int64(1), object(2)
memory usage: 4.2+ MB